webtalk_init -webtalk_dir E:/study/3.lesson_for_fpga/1.fir_low_pass/1.fir_low_pass.sim/sim_1/behav/xsim/xsim.dir/tb_fir_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Dec 11 19:25:50 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "84691b8e-75b9-4b3e-91c3-66903e1cd193" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "23542f7045fd474f8fe0ce59921213ec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "128" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600 6-Core Processor              " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "901 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.53_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16336_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2735387921 -regid "" -xml E:/study/3.lesson_for_fpga/1.fir_low_pass/1.fir_low_pass.sim/sim_1/behav/xsim/xsim.dir/tb_fir_top_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/study/3.lesson_for_fpga/1.fir_low_pass/1.fir_low_pass.sim/sim_1/behav/xsim/xsim.dir/tb_fir_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/study/3.lesson_for_fpga/1.fir_low_pass/1.fir_low_pass.sim/sim_1/behav/xsim/xsim.dir/tb_fir_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
