# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/study/3.lesson_for_fpga/1.fir_low_pass/1.fir_low_pass.srcs/sources_1/ip/dds_5M/dds_5M.xci
# IP: The module: 'dds_5M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/3.lesson_for_fpga/1.fir_low_pass/1.fir_low_pass.srcs/sources_1/ip/dds_5M/dds_5M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_5M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/study/3.lesson_for_fpga/1.fir_low_pass/1.fir_low_pass.srcs/sources_1/ip/dds_5M/dds_5M.xci
# IP: The module: 'dds_5M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/3.lesson_for_fpga/1.fir_low_pass/1.fir_low_pass.srcs/sources_1/ip/dds_5M/dds_5M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_5M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
